theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment

deploy:
  type: git
  repo: https://github.com/ClareChu/clarechu.github.io
  branch: themes
  message: "init"



# post_asset_folder: true